# Generated by Django 4.2.6 on 2023-10-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='moive',
            new_name='movie',
        ),
    ]
