# Generated by Django 4.2.6 on 2023-10-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_moive_reservation_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Movie',
            new_name='movie',
        ),
    ]
